# Site settings
title: plan4d2
email: colinn@outlook.com
description: > # Do it!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.plan4d2.com # the base hostname & protocol for your site
twitter_username: colinnex
github_username:  colinnex

# outputting
permalink: none

# Build settings
markdown: kramdown
highlighter: rouge
